[build-system]
requires = [
    "setuptools>=68",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyLnLib"
version = "0.1.46"
description = "Libreria personale di utility Python"
authors = [
    { name = "Loreto Notarantonio" },
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "bs4>=0.0.2",
    "ebooklib>=0.20",
    "PyYAML>=6.0.2",
    "tomli-w>=1.0.0",
]

[project.license]
text = "MIT"

[tool.ruff.lint]
ignore = [
    "E402",
    "E702",
    "E401",
    "E701",
]

[tool.ruff.lint.isort]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "standard"
reportUnusedVariable = "warning"
reportUnusedImport = "warning"
reportOptionalMemberAccess = "warning"
reportMissingTypeStubs = false

[tool.setuptools.packages.find]
where = [
    "src",
]
